//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueJackCake
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string CakeName { get; set; }
        public string Price { get; set; }
        public string Stock { get; set; }
        public byte[] Picture { get; set; }
    }
}
